### ISSUE TITLE
Investigate opencv cuda implementation

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc_kinect#9]
Creating this issue because there is a branch that does not have an issue.

@nachoreimat please either explain the issue, or close it and delete the branch.

**Comment by nachoreimat** [comment]
I tried implementing our OpenCV filtering using CUDA functions but the performance was worst than using the CPU ones. So I stopped this implementation

**Comment by jackjansen** [comment]
So, should we delete the branch and close the issue?

**Comment by nachoreimat** [comment]
Sure
